### ISSUE TITLE
[Feature Request] Limit Tweeten to only one instance

### ISSUE THREAD

**Issue by EmuAGR** [MehediH/TweetenSite#68]
I have Tweeten pinned to my taskbar so the Window opens next to my browser. The new "tray bar on close" is awesome, but when I want to restore it through my pinned icon, a second instance of Tweeten is launched instead of the old one.

Since Tweeten allows the usage of multiple accounts, I think instances should be limited to one (via checkbox or by default). Thank you for your support.

Version: 3.1 x64

**Comment by MehediH** [comment]
With Tweeten 2 you can limit Tweeten to only one instance if you enable Minimize To Tray.

**Comment by catlinman** [comment]
Hey! Somewhat reviving an old issue since it's still an annoyance.

I find that this should, as suggested by @EmuAGR, be default behavior since it's somewhat obscure that you have to enable the minimize to tray feature to do this. It makes pinning Tweeten to the taskbar impossible otherwise, as it always creates new instances that do not stack with the shortcut placed. For new users that do not know about this it could pose a major inconvenience when it comes to setting up the application.

Even without minimizing it should be limited to one instance unless further tweaking is used, since most users will not need more than one instance and even so: Shouldn't those instances be selectable and configurable then? The whole multiple instance thing just doesn't have too many practical uses I believe.
