### ISSUE TITLE
[Performance issue] Keyboard input extremely slow since the latest update

### ISSUE THREAD

**Issue by LoosGuccreen** [MehediH/TweetenSite#71]
Pretty much everything is in the title.

Since the latest update (0.1.160801-1900 channel beta), the keyboard input are extremely slow on my machine, no matter the source (I tried using a standard multidevice bluetooth keyboard, a logitech wireless pc keyboard and a corsair wired keyboard and for every keyboard it's the same).

I tried uninstalling/reinstalling the app but it didn't solve it (It didn't even log me out of tweetdeck so I guess the cache wasn't cleared but I don't know how to do that).

EDIT: I forgot to precise that it's only the keyboard input that is slow (and only on tweeten, it works fine on the other programs), the rest of the program (tweet update, gif playback, etc.) is doing fine

**Comment by MehediH** [comment]
This is an issue with Electron and we are trying to fix it. Not sure how long it'll take though.

**Comment by digiwombat** [comment]
I'll comment instead of popping a new issue. Is this also the reason for the UI lag? Basically, gifs/videos play as normal, but the Tweetdeck UI animations (scrolling back to top, new tweets scrolling in, New Tweet drawer opening, etc) are extremely laggy.

If it's not the same issue, I'll happily roll a new bug with an example video. It just started two versions ago.

**Comment by MehediH** [comment]
@LoosGuccreen @digiwombat Should be fixed with tomorrow's update.
